### ISSUE TITLE
License forbids usage by many projects

### ISSUE THREAD

**Issue by vdboor** [mbourqui/django-echoices#54]
Most of Python's libraries are BSD/MIT licensed for a reason: we can freely use each others code.

This project is GPLv3 licensed, meaning any project that uses this library MUST published under GPLv3 too. I also have to open all my website and application sources by using this library. Is this wat you consciously intended, or was that an accidental mistake?

Since we're the only copyright holders of this project, you can still freely change the license if you wish.

**Comment by mbourqui** [comment]
Thanks for you comment, I changed the license for a more open one!
